export const posDictionary = {
    "hi": "Greeting",
    "hello": "Greeting",
    "hey": "Greeting",
    "howdy": "Greeting",
    "greetings": "Greeting",
    "salutations": "Greeting",
    "good morning": "Greeting",
    "good afternoon": "Greeting",
    "good evening": "Greeting",
    "bye": "Farewell",
    "goodbye": "Farewell",
    "see you later": "Farewell",
    "take care": "Farewell",
    "farewell": "Farewell",
    "later": "Farewell",
    "yes": "Affirmation",
    "yeah": "Affirmation",
    "yep": "Affirmation",
    "sure": "Affirmation",
    "absolutely": "Affirmation",
    "no": "Negation",
    "nope": "Negation",
    "not at all": "Negation",
    "never": "Negation",
    "nah": "Negation",
    "maybe": "Uncertainty",
    "possibly": "Uncertainty",
    "likely": "Uncertainty",
    "certainly": "Affirmation",
    "definitely": "Affirmation",
    "awesome": "Positive",
    "great": "Positive",
    "fantastic": "Positive",
    "wonderful": "Positive",
    "okay": "Neutral",
    "fine": "Neutral",
    "alright": "Neutral",
    "sad": "Negative",
    "happy": "Positive",
    "angry": "Negative",
    "excited": "Positive",
    "confused": "Negative",
    "tired": "Negative",
    "bored": "Negative",
    "thank you": "Gratitude",
    "thanks": "Gratitude",
    "appreciate it": "Gratitude",
    "welcome": "Response",
    "no worries": "Response",
    "you bet": "Affirmation",
    "right": "Affirmation",
    "exactly": "Affirmation",
    "sure thing": "Affirmation",
    "absolutely not": "Negation",
    "not really": "Negation",
    "go ahead": "Permission",
    "feel free": "Permission",
    "let's go": "Action",
    "come here": "Action",
    "look out": "Warning",
    "watch out": "Warning",
    "congratulations": "Celebration",
    "well done": "Celebration",
    "good job": "Celebration",
    "best wishes": "Goodwill",
    "good luck": "Goodwill",
    "take it easy": "Goodbye",
    "catch you later": "Farewell",
    // Continue adding terms until we reach over 1000
};